server:
  port: 8761
eureka:
  client:
    # 表示是否将自己注册到Eureka Server，默认为true
    register-with-eureka: false
    # 表示是否从Eureka Server获取注册信息，默认为true
    fetch-registry: false
  server:
    # 设置同步为空时的等待时间。默认 5 * MINUTES
    waitTimeInMsWhenSyncEmpty: 0

