eureka:
  client:
    # 表示是否将自己注册到Eureka Server，默认为true
    register-with-eureka: false
    # 表示是否从Eureka Server获取注册信息，默认为true
    fetch-registry: true
spring:
  application:
    name: shopping-front
feign:
  hystrix:
    # 是否开启断路器
    enabled: true