server:
  port: 8081
spring:
  application:
    name: product-server
  profiles:
    active: dev
eureka:
  client:
    # 表示是否将自己注册到Eureka Server，默认为true
#    register-with-eureka: false
    # 表示是否从Eureka Server获取注册信息，默认为true
#    fetch-registry: false
    service-url:
      # 设置eureka服务地址
      defaultZone: http://localhost:8761/eureka
